// use std::{path::PathBuf, sync::Arc};

// use crate::{
//     library::TrackId,
//     queue::{Queue, loop_mode::LoopMode},
//     track::Track,
// };

// #[test]
// fn next() {
//     let mut queue = Queue::default();
//     let pathbuf_1 = PathBuf::from("../test_assets/test.flac");
//     let pathbuf_2 = PathBuf::from("../test_assets/test1.flac");

//     let mut id = TrackId::default();
//     queue.enqueue(Arc::new(
//         Track::new(pathbuf_1.as_path(), id.clone()).unwrap(),
//     ));
//     id.increment();
//     queue.enqueue(Arc::new(
//         Track::new(pathbuf_2.as_path(), id.clone()).unwrap(),
//     ));

//     assert!(queue.next());
//     assert_eq!(queue.current_track.as_ref().unwrap().pathbuf, pathbuf_1);

//     assert!(queue.next());
//     assert!(queue.current_track.is_some());
//     assert_eq!(queue.current_track.as_ref().unwrap().pathbuf, pathbuf_2);

//     assert!(!queue.next());
//     assert_eq!(queue.current_track.as_ref().unwrap().pathbuf, pathbuf_2);
// }

// #[test]
// fn prev() {
//     let mut queue = Queue::default();
//     let pathbuf_1 = PathBuf::from("../test_assets/test.flac");
//     let pathbuf_2 = PathBuf::from("../test_assets/test1.flac");

//     let mut id = TrackId::default();
//     queue.enqueue(Arc::new(
//         Track::new(pathbuf_1.as_path(), id.clone()).unwrap(),
//     ));
//     id.increment();
//     queue.enqueue(Arc::new(
//         Track::new(pathbuf_2.as_path(), id.clone()).unwrap(),
//     ));

//     assert!(!queue.prev());
//     assert!(queue.current_track.is_none());

//     queue.next();
//     queue.next();

//     assert!(queue.prev());
//     assert_eq!(queue.current_track.unwrap().pathbuf, pathbuf_1);
// }

// #[test]
// fn prepend() {
//     let mut queue = Queue::default();
//     let pathbuf_1 = PathBuf::from("../test_assets/test.flac");
//     let pathbuf_2 = PathBuf::from("../test_assets/test1.flac");

//     let mut id = TrackId::default();
//     queue.enqueue(Arc::new(
//         Track::new(pathbuf_1.as_path(), id.clone()).unwrap(),
//     ));
//     id.increment();
//     queue.prepend_queue(Arc::new(
//         Track::new(pathbuf_2.as_path(), id.clone()).unwrap(),
//     ));
//     queue.next();
//     assert_eq!(queue.current_track.unwrap().pathbuf, pathbuf_2);
// }

// // Below are generated by Claude

// fn make_track(path: &str, id: TrackId) -> Arc<Track> {
//     Arc::new(Track::new(PathBuf::from(path).as_path(), id).unwrap())
// }

// // ── enqueue / is_empty ───────────────────────────────────────────────────────

// #[test]
// fn enqueue_makes_non_empty() {
//     let mut queue = Queue::default();
//     assert!(queue.is_empty());
//     queue.enqueue(make_track("../test_assets/test.flac", TrackId::default()));
//     assert!(!queue.is_empty());
// }

// // ── dequeue ──────────────────────────────────────────────────────────────────

// #[test]
// fn dequeue_valid_index() {
//     let mut queue = Queue::default();
//     let mut id = TrackId::default();
//     queue.enqueue(make_track("../test_assets/test.flac", id));
//     id.increment();
//     queue.enqueue(make_track("../test_assets/test1.flac", id));

//     let removed = queue.dequeue(0);
//     assert!(removed.is_some());
//     assert_eq!(
//         removed.unwrap().pathbuf,
//         PathBuf::from("../test_assets/test.flac")
//     );
//     assert_eq!(queue.next_tracks.len(), 1);
// }

// #[test]
// fn dequeue_out_of_bounds_returns_none() {
//     let mut queue = Queue::default();
//     queue.enqueue(make_track("../test_assets/test.flac", TrackId::default()));
//     assert!(queue.dequeue(5).is_none());
// }

// // ── prepend_queue ─────────────────────────────────────────────────────────────

// #[test]
// fn prepend_queue_inserts_at_front() {
//     let mut queue = Queue::default();
//     let mut id = TrackId::default();
//     queue.enqueue(make_track("../test_assets/test.flac", id));
//     id.increment();
//     queue.prepend_queue(make_track("../test_assets/test1.flac", id));

//     // test1.flac was prepended, so next() should yield it first
//     queue.next();
//     assert_eq!(
//         queue.current_track.as_ref().unwrap().pathbuf,
//         PathBuf::from("../test_assets/test1.flac")
//     );
// }

// // ── clear ────────────────────────────────────────────────────────────────────

// #[test]
// fn clear_empties_all_tracks() {
//     let mut queue = Queue::default();
//     let t1 = Track::new(&PathBuf::from("../test_assets/test.flac")).unwrap();
//     let t2 = Track::new(&PathBuf::from("../test_assets/test1.flac")).unwrap();
//     queue.enqueue(Arc::new(t1));
//     queue.enqueue(Arc::new(t2));
//     queue.next(); // moves one to previous

//     queue.clear();

//     assert!(queue.next_tracks.is_empty());
//     assert!(queue.previous_tracks.is_empty());
//     // current_track is not cleared by clear()
// }

// // ── shuffle ──────────────────────────────────────────────────────────────────

// #[test]
// fn shuffle_preserves_all_elements() {
//     let mut queue = Queue::default();
//     let mut id = TrackId::default();
//     let paths = ["../test_assets/test.flac", "../test_assets/test1.flac"];
//     for path in &paths {
//         queue.enqueue(make_track(path, id));
//         id.increment();
//     }

//     let before: Vec<_> = queue
//         .next_tracks
//         .iter()
//         .map(|t| t.pathbuf.clone())
//         .collect();
//     queue.shuffle();
//     let after: Vec<_> = queue
//         .next_tracks
//         .iter()
//         .map(|t| t.pathbuf.clone())
//         .collect();

//     assert_eq!(before.len(), after.len());
//     for p in &before {
//         assert!(after.contains(p));
//     }
// }

// // ── cycle_loop_mode ──────────────────────────────────────────────────────────

// #[test]
// fn cycle_loop_mode_sequence() {
//     let mut queue = Queue::default();
//     assert!(matches!(queue.loop_mode, LoopMode::None));
//     queue.cycle_loop_mode();
//     assert!(matches!(queue.loop_mode, LoopMode::Queue));
//     queue.cycle_loop_mode();
//     assert!(matches!(queue.loop_mode, LoopMode::Track));
//     queue.cycle_loop_mode();
//     assert!(matches!(queue.loop_mode, LoopMode::None));
// }

// // ── restart ──────────────────────────────────────────────────────────────────

// #[test]
// fn restart_moves_all_tracks_to_next() {
//     let mut queue = Queue::default();
//     let mut id = TrackId::default();
//     queue.enqueue(make_track("../test_assets/test.flac", id));
//     id.increment();
//     queue.enqueue(make_track("../test_assets/test1.flac", id));
//     queue.next(); // test.flac → current
//     queue.next(); // test1.flac → current, test.flac → previous

//     queue.restart();

//     // current should be None; previous empty; next has all three in order
//     assert!(queue.current_track.is_none());
//     assert!(queue.previous_tracks.is_empty());
//     assert_eq!(queue.next_tracks.len(), 2);
//     assert_eq!(
//         queue.next_tracks[0].pathbuf,
//         PathBuf::from("../test_assets/test.flac")
//     );
// }

// // ── get_snapshot ─────────────────────────────────────────────────────────────

// #[test]
// fn get_snapshot_reflects_state() {
//     let mut queue = Queue::default();
//     let id = TrackId::default();
//     queue.enqueue(make_track("../test_assets/test.flac", id));
//     queue.next();

//     let snap = queue.get_snapshot();
//     assert!(snap.current_track.is_some());
//     assert!(snap.previous_tracks.is_empty());
//     assert!(snap.next_tracks.is_empty());
// }
