// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = { length: bigint, album: string | null, title: string, artist: string | null, disc_number: number | null, genre: string | null, year: number | null, cover_art_path: string | null, };
