// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackStatus } from "./playback";

export type PlayerSnapshot = { playback_status: PlaybackStatus, volume: number, playback_speed: number, position: { secs: number, nanos: number }, };
