// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Properties = { bitrate: number | null, bit_depth: number | null, channels: number | null, sample_rate: number | null, duration: { secs: number, nanos: number }, };
