// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopMode } from "./loop_mode";
import type { Track } from "./track";

export type QueueSnapshot = { loop_mode: LoopMode, current_track: Track | null, previous_tracks: Array<Track>, next_tracks: Array<Track>, };
