// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./metadata";
import type { Properties } from "./properties";
import type { TrackId } from "./track_id";

/**
 * Stores necessary information about a track.
 */
export type Track = { id: TrackId, pathbuf: string, metadata: Metadata, properties: Properties, };
