use std::path::Path;

use crate::player::{Playback, playback_status::PlaybackStatus};

#[test]
fn new() {
    assert!(Playback::new().is_ok())
}

#[test]
fn stopped() {
    let player = Playback::new().unwrap();
    assert_eq!(player.playback_status(), PlaybackStatus::Stopped);
}

#[tokio::test]
async fn play() {
    let player = Playback::new().unwrap();
    player
        .load_track(Path::new("../test_assets/test.flac"))
        .unwrap();
    player.play();
    assert_eq!(player.playback_status(), PlaybackStatus::Playing);
}

#[tokio::test]
async fn pause() {
    let player = Playback::new().unwrap();
    player
        .load_track(Path::new("../test_assets/test.flac"))
        .unwrap();
    player.pause();
    assert_eq!(player.playback_status(), PlaybackStatus::Paused);
}

// Below are generated by Claude
// ── volume ───────────────────────────────────────────────────────────────────

#[test]
fn default_volume_is_one() {
    let player = Playback::new().unwrap();
    assert!((player.volume() - 1.0f32).abs() < f32::EPSILON);
}

#[test]
fn set_volume() {
    let player = Playback::new().unwrap();
    player.set_volume(0.5);
    assert!((player.volume() - 0.5f32).abs() < 1e-5);
}

#[test]
fn increase_volume_clamps_at_two() {
    let player = Playback::new().unwrap();
    player.set_volume(1.9);
    player.increase_volume(0.5); // would be 2.4 without clamp
    assert!(player.volume() <= 2.0);
}

#[test]
fn decrease_volume_clamps_at_zero() {
    let player = Playback::new().unwrap();
    player.set_volume(0.1);
    player.decrease_volume(0.5); // would be -0.4 without clamp
    assert!(player.volume() >= 0.0);
}

#[test]
fn increase_then_decrease_volume() {
    let player = Playback::new().unwrap();
    player.set_volume(1.0);
    player.increase_volume(0.2);
    player.decrease_volume(0.2);
    assert!((player.volume() - 1.0f32).abs() < 1e-5);
}

// ── get_snapshot ─────────────────────────────────────────────────────────────

#[test]
fn snapshot_stopped_state() {
    use crate::player::playback_status::PlaybackStatus;
    let player = Playback::new().unwrap();
    let snap = player.get_snapshot();
    assert_eq!(snap.playback_status, PlaybackStatus::Stopped);
    assert!((snap.volume - 1.0f32).abs() < 1e-5);
    assert_eq!(snap.position.as_secs(), 0);
}

// ── toggle_play ───────────────────────────────────────────────────────────────

#[tokio::test]
async fn toggle_play_from_playing_pauses() {
    use crate::player::playback_status::PlaybackStatus;
    let player = Playback::new().unwrap();
    player
        .load_track(Path::new("../test_assets/test.flac"))
        .unwrap();
    player.play();
    assert_eq!(player.playback_status(), PlaybackStatus::Playing);
    player.toggle_play();
    assert_eq!(player.playback_status(), PlaybackStatus::Paused);
}

#[tokio::test]
async fn toggle_play_from_paused_plays() {
    use crate::player::playback_status::PlaybackStatus;
    let player = Playback::new().unwrap();
    player
        .load_track(Path::new("../test_assets/test.flac"))
        .unwrap();
    player.pause();
    player.toggle_play();
    assert_eq!(player.playback_status(), PlaybackStatus::Playing);
}

// ── load_track error ─────────────────────────────────────────────────────────

#[test]
fn load_track_nonexistent_returns_err() {
    let player = Playback::new().unwrap();
    assert!(
        player
            .load_track(Path::new("/nonexistent/audio.flac"))
            .is_err()
    );
}
